[package]
name = "valida-range"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-matrix = { path = "../../Plonky3/matrix" }

valida-machine = { path = "../machine" }
