[package]
name = "valida-machine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-air = { path = "../plonky3/air" }
p3-commit = { path = "../plonky3/commit" }
p3-field = { path = "../plonky3/field" }
p3-matrix = { path = "../plonky3/matrix" }
